services:

  node-red:
      build:
       context: .
      ports: 
        - "1880:1880"
      networks:
        - red-ntw

  web:  
      image: nginx
      ports: 
        - "80:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - node-red
      networks: 
        - red-ntw
networks:
    red-ntw:
      driver: bridge